from pathlib import Path
from datetime import datetime

def generate_markdown_report(
    save_dir: Path,
    model_name: str,
    feature_source: str,
    accuracy: float,
    classification_report_str: str,
    confusion_matrix_filename: str
):
    """
    Generate an experimental report in Markdown format.
    
    Parameters:
    ----------
    save_dir : Path
        Directory to save the report.
    model_name : str
        Name of the model (e.g., "RF", "SVM").
    feature_source : str
        Source of features ("Custom 63-dim" or "Official 561-dim").
    accuracy : float
        Validation accuracy.
    classification_report_str : str
        Detailed classification report string.
    confusion_matrix_filename : str
        Filename of the confusion matrix image (for embedding in Markdown).
    """
    
    # Get current timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Report filename (e.g., report_rf_custom.md)
    report_filename = f"report_{model_name.lower()}_{'custom' if 'Custom' in feature_source else 'official'}.md"
    report_path = save_dir / report_filename
    
    # Markdown content template
    content = f"""# HAR Experiment Report

**Date**: {timestamp}

## 1. Experiment Configuration
- **Model**: {model_name}
- **Feature Source**: {feature_source}

## 2. Results
- **Validation Accuracy**: **{accuracy:.2%}**

### Classification Report
```text
{classification_report_str}
```

## 3. Visualization
### Confusion Matrix
![Confusion Matrix]({confusion_matrix_filename})

---
*Generated by report.py*
"""
    
    # Write to file
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(content)
        
    print(f"Report generated: {report_path}")
